packages:
  - "src/*"

catalogs:
  cli:
    "@antfu/ni": 25.0.0
    "@isentinel/eslint-config": 3.0.0
    "@typescript-eslint/eslint-plugin": 8.39.0
    "@typescript-eslint/parser": 8.39.0
    "@typescript-eslint/utils": 8.39.0
    bumpp: 10.2.2
    eslint: 9.32.0
    eslint-plugin-pnpm: 1.1.0
    jiti: 2.5.1
    lint-staged: 16.1.4
    simple-git-hooks: 2.13.1
    ts-api-utils: 2.1.0
    tsdown: 0.13.3
    tsx: 4.20.3
    typescript: 5.8.3
  testing:
    "@vitest/eslint-plugin": 1.3.4
    eslint-plugin-eslint-plugin: 7.0.0
    eslint-plugin-n: 17.23.1
    eslint-vitest-rule-tester: 2.2.1
    publint: 0.3.12
    unplugin-unused: 0.5.1
    vitest: 3.2.4
  types:
    "@isentinel/tsconfig": 1.0.0
    "@types/node": 24.0.13
  utils:
    eslint-doc-generator: 2.2.2

configDependencies:
  "@pnpm/trusted-deps": 0.1.1+sha512-jI3PWNv2zCg9+KHI3qQTsa534c5nisZQrHFeWSyyHoUXcuzvjkXxQKPFLJ/qtNAF+PtKHDlRntO2aZKb3VDuHQ==

onlyBuiltDependencies:
  - unrs-resolver

onlyBuiltDependenciesFile: node_modules/.pnpm-config/@pnpm/trusted-deps/allow.json

catalogMode: strict
enablePrePostScripts: true
ignoreWorkspaceRootCheck: true
shellEmulator: true
